# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: hms
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmYzZGU3OTA5MTI3MzBiZTQ4N2E1N2IxMjRlYjQzNDhlMjJiNmJiZjk3Mjc5YmMyZTVjNjEwNWUzN2Q3MDMyMjFlMGIzZTUwMGY4MzlkNjRhN2I0ZTQ5ZWE0YzY3YjM2NWVjZDY3YTg4M2UzNWRjMTU1NjY1MzkxMGZlOWE4NTQ=
