package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AdHocChargeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdHocChargeAllPropertiesEquals(AdHocCharge expected, AdHocCharge actual) {
        assertAdHocChargeAutoGeneratedPropertiesEquals(expected, actual);
        assertAdHocChargeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdHocChargeAllUpdatablePropertiesEquals(AdHocCharge expected, AdHocCharge actual) {
        assertAdHocChargeUpdatableFieldsEquals(expected, actual);
        assertAdHocChargeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdHocChargeAutoGeneratedPropertiesEquals(AdHocCharge expected, AdHocCharge actual) {
        assertThat(actual)
            .as("Verify AdHocCharge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdHocChargeUpdatableFieldsEquals(AdHocCharge expected, AdHocCharge actual) {
        assertThat(actual)
            .as("Verify AdHocCharge relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getAddedAt()).as("check addedAt").isEqualTo(expected.getAddedAt()))
            .satisfies(a -> assertThat(a.getVoidedAt()).as("check voidedAt").isEqualTo(expected.getVoidedAt()))
            .satisfies(a -> assertThat(a.getVoidReason()).as("check voidReason").isEqualTo(expected.getVoidReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdHocChargeUpdatableRelationshipsEquals(AdHocCharge expected, AdHocCharge actual) {
        assertThat(actual)
            .as("Verify AdHocCharge relationships")
            .satisfies(a -> assertThat(a.getAdmission()).as("check admission").isEqualTo(expected.getAdmission()))
            .satisfies(a -> assertThat(a.getServiceCatalogue()).as("check serviceCatalogue").isEqualTo(expected.getServiceCatalogue()));
    }
}
