package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdmissionTransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionTransferAllPropertiesEquals(AdmissionTransfer expected, AdmissionTransfer actual) {
        assertAdmissionTransferAutoGeneratedPropertiesEquals(expected, actual);
        assertAdmissionTransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionTransferAllUpdatablePropertiesEquals(AdmissionTransfer expected, AdmissionTransfer actual) {
        assertAdmissionTransferUpdatableFieldsEquals(expected, actual);
        assertAdmissionTransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionTransferAutoGeneratedPropertiesEquals(AdmissionTransfer expected, AdmissionTransfer actual) {
        assertThat(actual)
            .as("Verify AdmissionTransfer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionTransferUpdatableFieldsEquals(AdmissionTransfer expected, AdmissionTransfer actual) {
        assertThat(actual)
            .as("Verify AdmissionTransfer relevant properties")
            .satisfies(a -> assertThat(a.getTransferredAt()).as("check transferredAt").isEqualTo(expected.getTransferredAt()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionTransferUpdatableRelationshipsEquals(AdmissionTransfer expected, AdmissionTransfer actual) {
        assertThat(actual)
            .as("Verify AdmissionTransfer relationships")
            .satisfies(a -> assertThat(a.getAdmission()).as("check admission").isEqualTo(expected.getAdmission()))
            .satisfies(a -> assertThat(a.getFromBed()).as("check fromBed").isEqualTo(expected.getFromBed()))
            .satisfies(a -> assertThat(a.getToBed()).as("check toBed").isEqualTo(expected.getToBed()));
    }
}
