package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdmissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionAllPropertiesEquals(Admission expected, Admission actual) {
        assertAdmissionAutoGeneratedPropertiesEquals(expected, actual);
        assertAdmissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionAllUpdatablePropertiesEquals(Admission expected, Admission actual) {
        assertAdmissionUpdatableFieldsEquals(expected, actual);
        assertAdmissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionAutoGeneratedPropertiesEquals(Admission expected, Admission actual) {
        assertThat(actual)
            .as("Verify Admission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionUpdatableFieldsEquals(Admission expected, Admission actual) {
        assertThat(actual)
            .as("Verify Admission relevant properties")
            .satisfies(a -> assertThat(a.getAdmittedAt()).as("check admittedAt").isEqualTo(expected.getAdmittedAt()))
            .satisfies(a -> assertThat(a.getAdmissionReason()).as("check admissionReason").isEqualTo(expected.getAdmissionReason()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDischargedAt()).as("check dischargedAt").isEqualTo(expected.getDischargedAt()))
            .satisfies(a -> assertThat(a.getDischargeNote()).as("check dischargeNote").isEqualTo(expected.getDischargeNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdmissionUpdatableRelationshipsEquals(Admission expected, Admission actual) {
        assertThat(actual)
            .as("Verify Admission relationships")
            .satisfies(a -> assertThat(a.getVisit()).as("check visit").isEqualTo(expected.getVisit()))
            .satisfies(a -> assertThat(a.getBed()).as("check bed").isEqualTo(expected.getBed()));
    }
}
