package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BedAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedAllPropertiesEquals(Bed expected, Bed actual) {
        assertBedAutoGeneratedPropertiesEquals(expected, actual);
        assertBedAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedAllUpdatablePropertiesEquals(Bed expected, Bed actual) {
        assertBedUpdatableFieldsEquals(expected, actual);
        assertBedUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedAutoGeneratedPropertiesEquals(Bed expected, Bed actual) {
        assertThat(actual)
            .as("Verify Bed auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedUpdatableFieldsEquals(Bed expected, Bed actual) {
        assertThat(actual)
            .as("Verify Bed relevant properties")
            .satisfies(a -> assertThat(a.getBedNumber()).as("check bedNumber").isEqualTo(expected.getBedNumber()))
            .satisfies(a ->
                assertThat(a.getDailyRateOverride())
                    .as("check dailyRateOverride")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDailyRateOverride())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedUpdatableRelationshipsEquals(Bed expected, Bed actual) {
        assertThat(actual)
            .as("Verify Bed relationships")
            .satisfies(a -> assertThat(a.getWard()).as("check ward").isEqualTo(expected.getWard()))
            .satisfies(a -> assertThat(a.getBedType()).as("check bedType").isEqualTo(expected.getBedType()));
    }
}
