package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BedTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedTypeAllPropertiesEquals(BedType expected, BedType actual) {
        assertBedTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertBedTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedTypeAllUpdatablePropertiesEquals(BedType expected, BedType actual) {
        assertBedTypeUpdatableFieldsEquals(expected, actual);
        assertBedTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedTypeAutoGeneratedPropertiesEquals(BedType expected, BedType actual) {
        assertThat(actual)
            .as("Verify BedType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedTypeUpdatableFieldsEquals(BedType expected, BedType actual) {
        assertThat(actual)
            .as("Verify BedType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a ->
                assertThat(a.getDefaultDailyRate())
                    .as("check defaultDailyRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDefaultDailyRate())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBedTypeUpdatableRelationshipsEquals(BedType expected, BedType actual) {
        // empty method
    }
}
