package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAllPropertiesEquals(Bill expected, Bill actual) {
        assertBillAutoGeneratedPropertiesEquals(expected, actual);
        assertBillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAllUpdatablePropertiesEquals(Bill expected, Bill actual) {
        assertBillUpdatableFieldsEquals(expected, actual);
        assertBillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAutoGeneratedPropertiesEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillUpdatableFieldsEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill relevant properties")
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPaidAt()).as("check paidAt").isEqualTo(expected.getPaidAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillUpdatableRelationshipsEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()));
    }
}
