package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillLineItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillLineItemAllPropertiesEquals(BillLineItem expected, BillLineItem actual) {
        assertBillLineItemAutoGeneratedPropertiesEquals(expected, actual);
        assertBillLineItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillLineItemAllUpdatablePropertiesEquals(BillLineItem expected, BillLineItem actual) {
        assertBillLineItemUpdatableFieldsEquals(expected, actual);
        assertBillLineItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillLineItemAutoGeneratedPropertiesEquals(BillLineItem expected, BillLineItem actual) {
        assertThat(actual)
            .as("Verify BillLineItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillLineItemUpdatableFieldsEquals(BillLineItem expected, BillLineItem actual) {
        assertThat(actual)
            .as("Verify BillLineItem relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getSourceType()).as("check sourceType").isEqualTo(expected.getSourceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillLineItemUpdatableRelationshipsEquals(BillLineItem expected, BillLineItem actual) {
        assertThat(actual)
            .as("Verify BillLineItem relationships")
            .satisfies(a -> assertThat(a.getBill()).as("check bill").isEqualTo(expected.getBill()));
    }
}
