package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsultationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultationAllPropertiesEquals(Consultation expected, Consultation actual) {
        assertConsultationAutoGeneratedPropertiesEquals(expected, actual);
        assertConsultationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultationAllUpdatablePropertiesEquals(Consultation expected, Consultation actual) {
        assertConsultationUpdatableFieldsEquals(expected, actual);
        assertConsultationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultationAutoGeneratedPropertiesEquals(Consultation expected, Consultation actual) {
        assertThat(actual)
            .as("Verify Consultation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultationUpdatableFieldsEquals(Consultation expected, Consultation actual) {
        assertThat(actual)
            .as("Verify Consultation relevant properties")
            .satisfies(a ->
                assertThat(a.getPresentingComplaint()).as("check presentingComplaint").isEqualTo(expected.getPresentingComplaint())
            )
            .satisfies(a ->
                assertThat(a.getExaminationFindings()).as("check examinationFindings").isEqualTo(expected.getExaminationFindings())
            )
            .satisfies(a -> assertThat(a.getDiagnosisOther()).as("check diagnosisOther").isEqualTo(expected.getDiagnosisOther()))
            .satisfies(a -> assertThat(a.getObservations()).as("check observations").isEqualTo(expected.getObservations()))
            .satisfies(a ->
                assertThat(a.getFollowUpInstructions()).as("check followUpInstructions").isEqualTo(expected.getFollowUpInstructions())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultationUpdatableRelationshipsEquals(Consultation expected, Consultation actual) {
        assertThat(actual)
            .as("Verify Consultation relationships")
            .satisfies(a -> assertThat(a.getDiagnoseses()).as("check diagnoseses").isEqualTo(expected.getDiagnoseses()));
    }
}
