package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiagnosticOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticOrderAllPropertiesEquals(DiagnosticOrder expected, DiagnosticOrder actual) {
        assertDiagnosticOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertDiagnosticOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticOrderAllUpdatablePropertiesEquals(DiagnosticOrder expected, DiagnosticOrder actual) {
        assertDiagnosticOrderUpdatableFieldsEquals(expected, actual);
        assertDiagnosticOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticOrderAutoGeneratedPropertiesEquals(DiagnosticOrder expected, DiagnosticOrder actual) {
        assertThat(actual)
            .as("Verify DiagnosticOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticOrderUpdatableFieldsEquals(DiagnosticOrder expected, DiagnosticOrder actual) {
        assertThat(actual)
            .as("Verify DiagnosticOrder relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTestName()).as("check testName").isEqualTo(expected.getTestName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getOrderedAt()).as("check orderedAt").isEqualTo(expected.getOrderedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticOrderUpdatableRelationshipsEquals(DiagnosticOrder expected, DiagnosticOrder actual) {
        assertThat(actual)
            .as("Verify DiagnosticOrder relationships")
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getVisit()).as("check visit").isEqualTo(expected.getVisit()))
            .satisfies(a -> assertThat(a.getLabTest()).as("check labTest").isEqualTo(expected.getLabTest()))
            .satisfies(a -> assertThat(a.getRadiologyExam()).as("check radiologyExam").isEqualTo(expected.getRadiologyExam()));
    }
}
