package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiagnosisAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosisAllPropertiesEquals(Diagnosis expected, Diagnosis actual) {
        assertDiagnosisAutoGeneratedPropertiesEquals(expected, actual);
        assertDiagnosisAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosisAllUpdatablePropertiesEquals(Diagnosis expected, Diagnosis actual) {
        assertDiagnosisUpdatableFieldsEquals(expected, actual);
        assertDiagnosisUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosisAutoGeneratedPropertiesEquals(Diagnosis expected, Diagnosis actual) {
        assertThat(actual)
            .as("Verify Diagnosis auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosisUpdatableFieldsEquals(Diagnosis expected, Diagnosis actual) {
        assertThat(actual)
            .as("Verify Diagnosis relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosisUpdatableRelationshipsEquals(Diagnosis expected, Diagnosis actual) {
        assertThat(actual)
            .as("Verify Diagnosis relationships")
            .satisfies(a -> assertThat(a.getConsultationses()).as("check consultationses").isEqualTo(expected.getConsultationses()));
    }
}
