package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DispenseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseAllPropertiesEquals(Dispense expected, Dispense actual) {
        assertDispenseAutoGeneratedPropertiesEquals(expected, actual);
        assertDispenseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseAllUpdatablePropertiesEquals(Dispense expected, Dispense actual) {
        assertDispenseUpdatableFieldsEquals(expected, actual);
        assertDispenseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseAutoGeneratedPropertiesEquals(Dispense expected, Dispense actual) {
        assertThat(actual)
            .as("Verify Dispense auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseUpdatableFieldsEquals(Dispense expected, Dispense actual) {
        assertThat(actual)
            .as("Verify Dispense relevant properties")
            .satisfies(a -> assertThat(a.getDispensedAt()).as("check dispensedAt").isEqualTo(expected.getDispensedAt()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseUpdatableRelationshipsEquals(Dispense expected, Dispense actual) {
        assertThat(actual)
            .as("Verify Dispense relationships")
            .satisfies(a -> assertThat(a.getPrescription()).as("check prescription").isEqualTo(expected.getPrescription()));
    }
}
