package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DispenseLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseLineAllPropertiesEquals(DispenseLine expected, DispenseLine actual) {
        assertDispenseLineAutoGeneratedPropertiesEquals(expected, actual);
        assertDispenseLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseLineAllUpdatablePropertiesEquals(DispenseLine expected, DispenseLine actual) {
        assertDispenseLineUpdatableFieldsEquals(expected, actual);
        assertDispenseLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseLineAutoGeneratedPropertiesEquals(DispenseLine expected, DispenseLine actual) {
        assertThat(actual)
            .as("Verify DispenseLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseLineUpdatableFieldsEquals(DispenseLine expected, DispenseLine actual) {
        assertThat(actual)
            .as("Verify DispenseLine relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getSubstitutionReason()).as("check substitutionReason").isEqualTo(expected.getSubstitutionReason())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDispenseLineUpdatableRelationshipsEquals(DispenseLine expected, DispenseLine actual) {
        assertThat(actual)
            .as("Verify DispenseLine relationships")
            .satisfies(a -> assertThat(a.getDispense()).as("check dispense").isEqualTo(expected.getDispense()))
            .satisfies(a -> assertThat(a.getPrescriptionLine()).as("check prescriptionLine").isEqualTo(expected.getPrescriptionLine()))
            .satisfies(a -> assertThat(a.getDrug()).as("check drug").isEqualTo(expected.getDrug()));
    }
}
