package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoctorOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorOrderAllPropertiesEquals(DoctorOrder expected, DoctorOrder actual) {
        assertDoctorOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorOrderAllUpdatablePropertiesEquals(DoctorOrder expected, DoctorOrder actual) {
        assertDoctorOrderUpdatableFieldsEquals(expected, actual);
        assertDoctorOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorOrderAutoGeneratedPropertiesEquals(DoctorOrder expected, DoctorOrder actual) {
        assertThat(actual)
            .as("Verify DoctorOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorOrderUpdatableFieldsEquals(DoctorOrder expected, DoctorOrder actual) {
        assertThat(actual)
            .as("Verify DoctorOrder relevant properties")
            .satisfies(a -> assertThat(a.getOrderedAt()).as("check orderedAt").isEqualTo(expected.getOrderedAt()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRecurrence()).as("check recurrence").isEqualTo(expected.getRecurrence()))
            .satisfies(a -> assertThat(a.getFrequency()).as("check frequency").isEqualTo(expected.getFrequency()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCancelledAt()).as("check cancelledAt").isEqualTo(expected.getCancelledAt()))
            .satisfies(a -> assertThat(a.getCancelReason()).as("check cancelReason").isEqualTo(expected.getCancelReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorOrderUpdatableRelationshipsEquals(DoctorOrder expected, DoctorOrder actual) {
        assertThat(actual)
            .as("Verify DoctorOrder relationships")
            .satisfies(a -> assertThat(a.getAdmission()).as("check admission").isEqualTo(expected.getAdmission()));
    }
}
