package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DrugAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrugAllPropertiesEquals(Drug expected, Drug actual) {
        assertDrugAutoGeneratedPropertiesEquals(expected, actual);
        assertDrugAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrugAllUpdatablePropertiesEquals(Drug expected, Drug actual) {
        assertDrugUpdatableFieldsEquals(expected, actual);
        assertDrugUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrugAutoGeneratedPropertiesEquals(Drug expected, Drug actual) {
        assertThat(actual)
            .as("Verify Drug auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrugUpdatableFieldsEquals(Drug expected, Drug actual) {
        assertThat(actual)
            .as("Verify Drug relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getCurrentStock()).as("check currentStock").isEqualTo(expected.getCurrentStock()))
            .satisfies(a -> assertThat(a.getReservedStock()).as("check reservedStock").isEqualTo(expected.getReservedStock()))
            .satisfies(a -> assertThat(a.getLowStockThreshold()).as("check lowStockThreshold").isEqualTo(expected.getLowStockThreshold()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getClassification()).as("check classification").isEqualTo(expected.getClassification()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrugUpdatableRelationshipsEquals(Drug expected, Drug actual) {
        // empty method
    }
}
