package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HospitalServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHospitalServiceAllPropertiesEquals(HospitalService expected, HospitalService actual) {
        assertHospitalServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertHospitalServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHospitalServiceAllUpdatablePropertiesEquals(HospitalService expected, HospitalService actual) {
        assertHospitalServiceUpdatableFieldsEquals(expected, actual);
        assertHospitalServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHospitalServiceAutoGeneratedPropertiesEquals(HospitalService expected, HospitalService actual) {
        assertThat(actual)
            .as("Verify HospitalService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHospitalServiceUpdatableFieldsEquals(HospitalService expected, HospitalService actual) {
        assertThat(actual)
            .as("Verify HospitalService relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getServiceType()).as("check serviceType").isEqualTo(expected.getServiceType()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHospitalServiceUpdatableRelationshipsEquals(HospitalService expected, HospitalService actual) {
        // empty method
    }
}
