package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InpatientVitalsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInpatientVitalsAllPropertiesEquals(InpatientVitals expected, InpatientVitals actual) {
        assertInpatientVitalsAutoGeneratedPropertiesEquals(expected, actual);
        assertInpatientVitalsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInpatientVitalsAllUpdatablePropertiesEquals(InpatientVitals expected, InpatientVitals actual) {
        assertInpatientVitalsUpdatableFieldsEquals(expected, actual);
        assertInpatientVitalsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInpatientVitalsAutoGeneratedPropertiesEquals(InpatientVitals expected, InpatientVitals actual) {
        assertThat(actual)
            .as("Verify InpatientVitals auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInpatientVitalsUpdatableFieldsEquals(InpatientVitals expected, InpatientVitals actual) {
        assertThat(actual)
            .as("Verify InpatientVitals relevant properties")
            .satisfies(a -> assertThat(a.getRecordedAt()).as("check recordedAt").isEqualTo(expected.getRecordedAt()))
            .satisfies(a ->
                assertThat(a.getTemperature())
                    .as("check temperature")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTemperature())
            )
            .satisfies(a -> assertThat(a.getPulseRate()).as("check pulseRate").isEqualTo(expected.getPulseRate()))
            .satisfies(a -> assertThat(a.getSystolicBp()).as("check systolicBp").isEqualTo(expected.getSystolicBp()))
            .satisfies(a -> assertThat(a.getDiastolicBp()).as("check diastolicBp").isEqualTo(expected.getDiastolicBp()))
            .satisfies(a -> assertThat(a.getOxygenSaturation()).as("check oxygenSaturation").isEqualTo(expected.getOxygenSaturation()))
            .satisfies(a ->
                assertThat(a.getWeight()).as("check weight").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeight())
            )
            .satisfies(a ->
                assertThat(a.getHeight()).as("check height").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHeight())
            )
            .satisfies(a -> assertThat(a.getBmi()).as("check bmi").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBmi()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInpatientVitalsUpdatableRelationshipsEquals(InpatientVitals expected, InpatientVitals actual) {
        assertThat(actual)
            .as("Verify InpatientVitals relationships")
            .satisfies(a -> assertThat(a.getAdmission()).as("check admission").isEqualTo(expected.getAdmission()));
    }
}
