package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LabTestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabTestAllPropertiesEquals(LabTest expected, LabTest actual) {
        assertLabTestAutoGeneratedPropertiesEquals(expected, actual);
        assertLabTestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabTestAllUpdatablePropertiesEquals(LabTest expected, LabTest actual) {
        assertLabTestUpdatableFieldsEquals(expected, actual);
        assertLabTestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabTestAutoGeneratedPropertiesEquals(LabTest expected, LabTest actual) {
        assertThat(actual)
            .as("Verify LabTest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabTestUpdatableFieldsEquals(LabTest expected, LabTest actual) {
        assertThat(actual)
            .as("Verify LabTest relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getSpecimenType()).as("check specimenType").isEqualTo(expected.getSpecimenType()))
            .satisfies(a ->
                assertThat(a.getTurnaroundTimeMinutes()).as("check turnaroundTimeMinutes").isEqualTo(expected.getTurnaroundTimeMinutes())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabTestUpdatableRelationshipsEquals(LabTest expected, LabTest actual) {
        // empty method
    }
}
