package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderExecutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderExecutionAllPropertiesEquals(OrderExecution expected, OrderExecution actual) {
        assertOrderExecutionAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderExecutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderExecutionAllUpdatablePropertiesEquals(OrderExecution expected, OrderExecution actual) {
        assertOrderExecutionUpdatableFieldsEquals(expected, actual);
        assertOrderExecutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderExecutionAutoGeneratedPropertiesEquals(OrderExecution expected, OrderExecution actual) {
        assertThat(actual)
            .as("Verify OrderExecution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderExecutionUpdatableFieldsEquals(OrderExecution expected, OrderExecution actual) {
        assertThat(actual)
            .as("Verify OrderExecution relevant properties")
            .satisfies(a -> assertThat(a.getExecutedAt()).as("check executedAt").isEqualTo(expected.getExecutedAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderExecutionUpdatableRelationshipsEquals(OrderExecution expected, OrderExecution actual) {
        assertThat(actual)
            .as("Verify OrderExecution relationships")
            .satisfies(a -> assertThat(a.getDoctorOrder()).as("check doctorOrder").isEqualTo(expected.getDoctorOrder()));
    }
}
