package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PatientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAllPropertiesEquals(Patient expected, Patient actual) {
        assertPatientAutoGeneratedPropertiesEquals(expected, actual);
        assertPatientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAllUpdatablePropertiesEquals(Patient expected, Patient actual) {
        assertPatientUpdatableFieldsEquals(expected, actual);
        assertPatientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAutoGeneratedPropertiesEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientUpdatableFieldsEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient relevant properties")
            .satisfies(a -> assertThat(a.getHospitalId()).as("check hospitalId").isEqualTo(expected.getHospitalId()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()))
            .satisfies(a -> assertThat(a.getEstimatedAge()).as("check estimatedAge").isEqualTo(expected.getEstimatedAge()))
            .satisfies(a -> assertThat(a.getSex()).as("check sex").isEqualTo(expected.getSex()))
            .satisfies(a -> assertThat(a.getSexEstimated()).as("check sexEstimated").isEqualTo(expected.getSexEstimated()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a ->
                assertThat(a.getIdentityDocumentType()).as("check identityDocumentType").isEqualTo(expected.getIdentityDocumentType())
            )
            .satisfies(a ->
                assertThat(a.getIdentityDocumentNumber()).as("check identityDocumentNumber").isEqualTo(expected.getIdentityDocumentNumber())
            )
            .satisfies(a -> assertThat(a.getOccupation()).as("check occupation").isEqualTo(expected.getOccupation()))
            .satisfies(a -> assertThat(a.getMaritalStatus()).as("check maritalStatus").isEqualTo(expected.getMaritalStatus()))
            .satisfies(a -> assertThat(a.getNextOfKinName()).as("check nextOfKinName").isEqualTo(expected.getNextOfKinName()))
            .satisfies(a -> assertThat(a.getNextOfKinPhone()).as("check nextOfKinPhone").isEqualTo(expected.getNextOfKinPhone()))
            .satisfies(a ->
                assertThat(a.getNextOfKinRelationship()).as("check nextOfKinRelationship").isEqualTo(expected.getNextOfKinRelationship())
            )
            .satisfies(a -> assertThat(a.getKnownAllergies()).as("check knownAllergies").isEqualTo(expected.getKnownAllergies()))
            .satisfies(a -> assertThat(a.getKnownConditions()).as("check knownConditions").isEqualTo(expected.getKnownConditions()))
            .satisfies(a -> assertThat(a.getVillageEstate()).as("check villageEstate").isEqualTo(expected.getVillageEstate()))
            .satisfies(a ->
                assertThat(a.getRegistrationStatus()).as("check registrationStatus").isEqualTo(expected.getRegistrationStatus())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientUpdatableRelationshipsEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient relationships")
            .satisfies(a -> assertThat(a.getMergedIntoPatient()).as("check mergedIntoPatient").isEqualTo(expected.getMergedIntoPatient()));
    }
}
