package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaymentPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentPlanAllPropertiesEquals(PaymentPlan expected, PaymentPlan actual) {
        assertPaymentPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentPlanAllUpdatablePropertiesEquals(PaymentPlan expected, PaymentPlan actual) {
        assertPaymentPlanUpdatableFieldsEquals(expected, actual);
        assertPaymentPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentPlanAutoGeneratedPropertiesEquals(PaymentPlan expected, PaymentPlan actual) {
        assertThat(actual)
            .as("Verify PaymentPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentPlanUpdatableFieldsEquals(PaymentPlan expected, PaymentPlan actual) {
        assertThat(actual)
            .as("Verify PaymentPlan relevant properties")
            .satisfies(a ->
                assertThat(a.getTotalOwed()).as("check totalOwed").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalOwed())
            )
            .satisfies(a -> assertThat(a.getAgreedAt()).as("check agreedAt").isEqualTo(expected.getAgreedAt()))
            .satisfies(a -> assertThat(a.getGuarantorName()).as("check guarantorName").isEqualTo(expected.getGuarantorName()))
            .satisfies(a ->
                assertThat(a.getGuarantorRelationship()).as("check guarantorRelationship").isEqualTo(expected.getGuarantorRelationship())
            )
            .satisfies(a -> assertThat(a.getGuarantorPhone()).as("check guarantorPhone").isEqualTo(expected.getGuarantorPhone()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentPlanUpdatableRelationshipsEquals(PaymentPlan expected, PaymentPlan actual) {
        assertThat(actual)
            .as("Verify PaymentPlan relationships")
            .satisfies(a -> assertThat(a.getBill()).as("check bill").isEqualTo(expected.getBill()));
    }
}
