package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrescriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAllPropertiesEquals(Prescription expected, Prescription actual) {
        assertPrescriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPrescriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAllUpdatablePropertiesEquals(Prescription expected, Prescription actual) {
        assertPrescriptionUpdatableFieldsEquals(expected, actual);
        assertPrescriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAutoGeneratedPropertiesEquals(Prescription expected, Prescription actual) {
        assertThat(actual)
            .as("Verify Prescription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionUpdatableFieldsEquals(Prescription expected, Prescription actual) {
        assertThat(actual)
            .as("Verify Prescription relevant properties")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getPrescribingSource()).as("check prescribingSource").isEqualTo(expected.getPrescribingSource()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionUpdatableRelationshipsEquals(Prescription expected, Prescription actual) {
        assertThat(actual)
            .as("Verify Prescription relationships")
            .satisfies(a -> assertThat(a.getVisit()).as("check visit").isEqualTo(expected.getVisit()));
    }
}
