package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrescriptionLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionLineAllPropertiesEquals(PrescriptionLine expected, PrescriptionLine actual) {
        assertPrescriptionLineAutoGeneratedPropertiesEquals(expected, actual);
        assertPrescriptionLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionLineAllUpdatablePropertiesEquals(PrescriptionLine expected, PrescriptionLine actual) {
        assertPrescriptionLineUpdatableFieldsEquals(expected, actual);
        assertPrescriptionLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionLineAutoGeneratedPropertiesEquals(PrescriptionLine expected, PrescriptionLine actual) {
        assertThat(actual)
            .as("Verify PrescriptionLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionLineUpdatableFieldsEquals(PrescriptionLine expected, PrescriptionLine actual) {
        assertThat(actual)
            .as("Verify PrescriptionLine relevant properties")
            .satisfies(a -> assertThat(a.getDosage()).as("check dosage").isEqualTo(expected.getDosage()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionLineUpdatableRelationshipsEquals(PrescriptionLine expected, PrescriptionLine actual) {
        assertThat(actual)
            .as("Verify PrescriptionLine relationships")
            .satisfies(a -> assertThat(a.getPrescription()).as("check prescription").isEqualTo(expected.getPrescription()))
            .satisfies(a -> assertThat(a.getDrug()).as("check drug").isEqualTo(expected.getDrug()));
    }
}
