package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RadiologyExamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRadiologyExamAllPropertiesEquals(RadiologyExam expected, RadiologyExam actual) {
        assertRadiologyExamAutoGeneratedPropertiesEquals(expected, actual);
        assertRadiologyExamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRadiologyExamAllUpdatablePropertiesEquals(RadiologyExam expected, RadiologyExam actual) {
        assertRadiologyExamUpdatableFieldsEquals(expected, actual);
        assertRadiologyExamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRadiologyExamAutoGeneratedPropertiesEquals(RadiologyExam expected, RadiologyExam actual) {
        assertThat(actual)
            .as("Verify RadiologyExam auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRadiologyExamUpdatableFieldsEquals(RadiologyExam expected, RadiologyExam actual) {
        assertThat(actual)
            .as("Verify RadiologyExam relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRadiologyExamUpdatableRelationshipsEquals(RadiologyExam expected, RadiologyExam actual) {
        // empty method
    }
}
