package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReferralAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralAllPropertiesEquals(Referral expected, Referral actual) {
        assertReferralAutoGeneratedPropertiesEquals(expected, actual);
        assertReferralAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralAllUpdatablePropertiesEquals(Referral expected, Referral actual) {
        assertReferralUpdatableFieldsEquals(expected, actual);
        assertReferralUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralAutoGeneratedPropertiesEquals(Referral expected, Referral actual) {
        assertThat(actual)
            .as("Verify Referral auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralUpdatableFieldsEquals(Referral expected, Referral actual) {
        assertThat(actual)
            .as("Verify Referral relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDestination()).as("check destination").isEqualTo(expected.getDestination()))
            .satisfies(a -> assertThat(a.getDestinationEmail()).as("check destinationEmail").isEqualTo(expected.getDestinationEmail()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralUpdatableRelationshipsEquals(Referral expected, Referral actual) {
        assertThat(actual)
            .as("Verify Referral relationships")
            .satisfies(a -> assertThat(a.getVisit()).as("check visit").isEqualTo(expected.getVisit()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()));
    }
}
