package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultAllPropertiesEquals(Result expected, Result actual) {
        assertResultAutoGeneratedPropertiesEquals(expected, actual);
        assertResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultAllUpdatablePropertiesEquals(Result expected, Result actual) {
        assertResultUpdatableFieldsEquals(expected, actual);
        assertResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultAutoGeneratedPropertiesEquals(Result expected, Result actual) {
        assertThat(actual)
            .as("Verify Result auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultUpdatableFieldsEquals(Result expected, Result actual) {
        assertThat(actual)
            .as("Verify Result relevant properties")
            .satisfies(a -> assertThat(a.getResultValue()).as("check resultValue").isEqualTo(expected.getResultValue()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getEnteredAt()).as("check enteredAt").isEqualTo(expected.getEnteredAt()))
            .satisfies(a -> assertThat(a.getImageReference()).as("check imageReference").isEqualTo(expected.getImageReference()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultUpdatableRelationshipsEquals(Result expected, Result actual) {
        // empty method
    }
}
