package com.hyperbrains.hms.domain;

import static com.hyperbrains.hms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VitalSignsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVitalSignsAllPropertiesEquals(VitalSigns expected, VitalSigns actual) {
        assertVitalSignsAutoGeneratedPropertiesEquals(expected, actual);
        assertVitalSignsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVitalSignsAllUpdatablePropertiesEquals(VitalSigns expected, VitalSigns actual) {
        assertVitalSignsUpdatableFieldsEquals(expected, actual);
        assertVitalSignsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVitalSignsAutoGeneratedPropertiesEquals(VitalSigns expected, VitalSigns actual) {
        assertThat(actual)
            .as("Verify VitalSigns auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVitalSignsUpdatableFieldsEquals(VitalSigns expected, VitalSigns actual) {
        assertThat(actual)
            .as("Verify VitalSigns relevant properties")
            .satisfies(a ->
                assertThat(a.getTemperature())
                    .as("check temperature")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTemperature())
            )
            .satisfies(a -> assertThat(a.getPulseRate()).as("check pulseRate").isEqualTo(expected.getPulseRate()))
            .satisfies(a -> assertThat(a.getSystolicBp()).as("check systolicBp").isEqualTo(expected.getSystolicBp()))
            .satisfies(a -> assertThat(a.getDiastolicBp()).as("check diastolicBp").isEqualTo(expected.getDiastolicBp()))
            .satisfies(a -> assertThat(a.getOxygenSaturation()).as("check oxygenSaturation").isEqualTo(expected.getOxygenSaturation()))
            .satisfies(a ->
                assertThat(a.getWeight()).as("check weight").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeight())
            )
            .satisfies(a ->
                assertThat(a.getHeight()).as("check height").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHeight())
            )
            .satisfies(a -> assertThat(a.getBmi()).as("check bmi").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBmi()))
            .satisfies(a -> assertThat(a.getNutritionalStatus()).as("check nutritionalStatus").isEqualTo(expected.getNutritionalStatus()))
            .satisfies(a ->
                assertThat(a.getPregnancyScreening()).as("check pregnancyScreening").isEqualTo(expected.getPregnancyScreening())
            )
            .satisfies(a -> assertThat(a.getTriageNotes()).as("check triageNotes").isEqualTo(expected.getTriageNotes()))
            .satisfies(a -> assertThat(a.getOtherMeasurements()).as("check otherMeasurements").isEqualTo(expected.getOtherMeasurements()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVitalSignsUpdatableRelationshipsEquals(VitalSigns expected, VitalSigns actual) {
        // empty method
    }
}
