package com.hyperbrains.hms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WardCoverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWardCoverAllPropertiesEquals(WardCover expected, WardCover actual) {
        assertWardCoverAutoGeneratedPropertiesEquals(expected, actual);
        assertWardCoverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWardCoverAllUpdatablePropertiesEquals(WardCover expected, WardCover actual) {
        assertWardCoverUpdatableFieldsEquals(expected, actual);
        assertWardCoverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWardCoverAutoGeneratedPropertiesEquals(WardCover expected, WardCover actual) {
        assertThat(actual)
            .as("Verify WardCover auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWardCoverUpdatableFieldsEquals(WardCover expected, WardCover actual) {
        assertThat(actual)
            .as("Verify WardCover relevant properties")
            .satisfies(a -> assertThat(a.getCoversFrom()).as("check coversFrom").isEqualTo(expected.getCoversFrom()))
            .satisfies(a -> assertThat(a.getCoversTo()).as("check coversTo").isEqualTo(expected.getCoversTo()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWardCoverUpdatableRelationshipsEquals(WardCover expected, WardCover actual) {
        assertThat(actual)
            .as("Verify WardCover relationships")
            .satisfies(a -> assertThat(a.getWard()).as("check ward").isEqualTo(expected.getWard()));
    }
}
