export enum PrescriptionStatus {
  PENDING = 'PENDING',

  READY_FOR_DISPENSE = 'READY_FOR_DISPENSE',

  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',

  DISPENSED = 'DISPENSED',

  PENDING_PAYMENT = 'PENDING_PAYMENT',

  PAID = 'PAID',
}
