export enum VisitStatus {
  REGISTERED = 'REGISTERED',

  WAITING_VITALS = 'WAITING_VITALS',

  IN_VITALS = 'IN_VITALS',

  WAITING_DOCTOR = 'WAITING_DOCTOR',

  IN_CONSULTATION = 'IN_CONSULTATION',

  WAITING_RESULTS = 'WAITING_RESULTS',

  WAITING_PAYMENT = 'WAITING_PAYMENT',

  CLOSED = 'CLOSED',

  CANCELLED = 'CANCELLED',
}
